// flow-typed signature: b4223db60ee3b65969c7f7b40a6b3980
// flow-typed version: <<STUB>>/csscomb_v^4.2.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csscomb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csscomb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csscomb/lib/cli' {
  declare module.exports: any;
}

declare module 'csscomb/lib/core' {
  declare module.exports: any;
}

declare module 'csscomb/lib/csscomb' {
  declare module.exports: any;
}

declare module 'csscomb/lib/errors' {
  declare module.exports: any;
}

declare module 'csscomb/lib/format' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/always-semicolon' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/block-indent' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/color-case' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/color-shorthand' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/element-case' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/eof-newline' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/leading-zero' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/lines-between-rulesets' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/quotes' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/remove-empty-rulesets' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/sort-order-fallback' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/sort-order' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/space-after-colon' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/space-after-combinator' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/space-after-opening-brace' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/space-after-selector-delimiter' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/space-before-closing-brace' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/space-before-colon' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/space-before-combinator' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/space-before-opening-brace' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/space-before-selector-delimiter' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/space-between-declarations' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/strip-spaces' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/tab-size' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/unitless-zero' {
  declare module.exports: any;
}

declare module 'csscomb/lib/options/vendor-prefix-align' {
  declare module.exports: any;
}

declare module 'csscomb/lib/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csscomb/lib/cli.js' {
  declare module.exports: $Exports<'csscomb/lib/cli'>;
}
declare module 'csscomb/lib/core.js' {
  declare module.exports: $Exports<'csscomb/lib/core'>;
}
declare module 'csscomb/lib/csscomb.js' {
  declare module.exports: $Exports<'csscomb/lib/csscomb'>;
}
declare module 'csscomb/lib/errors.js' {
  declare module.exports: $Exports<'csscomb/lib/errors'>;
}
declare module 'csscomb/lib/format.js' {
  declare module.exports: $Exports<'csscomb/lib/format'>;
}
declare module 'csscomb/lib/options/always-semicolon.js' {
  declare module.exports: $Exports<'csscomb/lib/options/always-semicolon'>;
}
declare module 'csscomb/lib/options/block-indent.js' {
  declare module.exports: $Exports<'csscomb/lib/options/block-indent'>;
}
declare module 'csscomb/lib/options/color-case.js' {
  declare module.exports: $Exports<'csscomb/lib/options/color-case'>;
}
declare module 'csscomb/lib/options/color-shorthand.js' {
  declare module.exports: $Exports<'csscomb/lib/options/color-shorthand'>;
}
declare module 'csscomb/lib/options/element-case.js' {
  declare module.exports: $Exports<'csscomb/lib/options/element-case'>;
}
declare module 'csscomb/lib/options/eof-newline.js' {
  declare module.exports: $Exports<'csscomb/lib/options/eof-newline'>;
}
declare module 'csscomb/lib/options/leading-zero.js' {
  declare module.exports: $Exports<'csscomb/lib/options/leading-zero'>;
}
declare module 'csscomb/lib/options/lines-between-rulesets.js' {
  declare module.exports: $Exports<'csscomb/lib/options/lines-between-rulesets'>;
}
declare module 'csscomb/lib/options/quotes.js' {
  declare module.exports: $Exports<'csscomb/lib/options/quotes'>;
}
declare module 'csscomb/lib/options/remove-empty-rulesets.js' {
  declare module.exports: $Exports<'csscomb/lib/options/remove-empty-rulesets'>;
}
declare module 'csscomb/lib/options/sort-order-fallback.js' {
  declare module.exports: $Exports<'csscomb/lib/options/sort-order-fallback'>;
}
declare module 'csscomb/lib/options/sort-order.js' {
  declare module.exports: $Exports<'csscomb/lib/options/sort-order'>;
}
declare module 'csscomb/lib/options/space-after-colon.js' {
  declare module.exports: $Exports<'csscomb/lib/options/space-after-colon'>;
}
declare module 'csscomb/lib/options/space-after-combinator.js' {
  declare module.exports: $Exports<'csscomb/lib/options/space-after-combinator'>;
}
declare module 'csscomb/lib/options/space-after-opening-brace.js' {
  declare module.exports: $Exports<'csscomb/lib/options/space-after-opening-brace'>;
}
declare module 'csscomb/lib/options/space-after-selector-delimiter.js' {
  declare module.exports: $Exports<'csscomb/lib/options/space-after-selector-delimiter'>;
}
declare module 'csscomb/lib/options/space-before-closing-brace.js' {
  declare module.exports: $Exports<'csscomb/lib/options/space-before-closing-brace'>;
}
declare module 'csscomb/lib/options/space-before-colon.js' {
  declare module.exports: $Exports<'csscomb/lib/options/space-before-colon'>;
}
declare module 'csscomb/lib/options/space-before-combinator.js' {
  declare module.exports: $Exports<'csscomb/lib/options/space-before-combinator'>;
}
declare module 'csscomb/lib/options/space-before-opening-brace.js' {
  declare module.exports: $Exports<'csscomb/lib/options/space-before-opening-brace'>;
}
declare module 'csscomb/lib/options/space-before-selector-delimiter.js' {
  declare module.exports: $Exports<'csscomb/lib/options/space-before-selector-delimiter'>;
}
declare module 'csscomb/lib/options/space-between-declarations.js' {
  declare module.exports: $Exports<'csscomb/lib/options/space-between-declarations'>;
}
declare module 'csscomb/lib/options/strip-spaces.js' {
  declare module.exports: $Exports<'csscomb/lib/options/strip-spaces'>;
}
declare module 'csscomb/lib/options/tab-size.js' {
  declare module.exports: $Exports<'csscomb/lib/options/tab-size'>;
}
declare module 'csscomb/lib/options/unitless-zero.js' {
  declare module.exports: $Exports<'csscomb/lib/options/unitless-zero'>;
}
declare module 'csscomb/lib/options/vendor-prefix-align.js' {
  declare module.exports: $Exports<'csscomb/lib/options/vendor-prefix-align'>;
}
declare module 'csscomb/lib/plugin.js' {
  declare module.exports: $Exports<'csscomb/lib/plugin'>;
}
