// flow-typed signature: ee26e12502ca6a84076b33b9c0be7fcd
// flow-typed version: <<STUB>>/wdio-appium-service_v^0.2.3/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wdio-appium-service'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wdio-appium-service' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wdio-appium-service/build/launcher' {
  declare module.exports: any;
}

declare module 'wdio-appium-service/gruntfile' {
  declare module.exports: any;
}

declare module 'wdio-appium-service/launcher' {
  declare module.exports: any;
}

declare module 'wdio-appium-service/lib/launcher' {
  declare module.exports: any;
}

declare module 'wdio-appium-service/test/integration/smoke_test' {
  declare module.exports: any;
}

declare module 'wdio-appium-service/test/integration/wdio.conf' {
  declare module.exports: any;
}

declare module 'wdio-appium-service/test/unit/launcher.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wdio-appium-service/build/launcher.js' {
  declare module.exports: $Exports<'wdio-appium-service/build/launcher'>;
}
declare module 'wdio-appium-service/gruntfile.js' {
  declare module.exports: $Exports<'wdio-appium-service/gruntfile'>;
}
declare module 'wdio-appium-service/index' {
  declare module.exports: $Exports<'wdio-appium-service'>;
}
declare module 'wdio-appium-service/index.js' {
  declare module.exports: $Exports<'wdio-appium-service'>;
}
declare module 'wdio-appium-service/launcher.js' {
  declare module.exports: $Exports<'wdio-appium-service/launcher'>;
}
declare module 'wdio-appium-service/lib/launcher.js' {
  declare module.exports: $Exports<'wdio-appium-service/lib/launcher'>;
}
declare module 'wdio-appium-service/test/integration/smoke_test.js' {
  declare module.exports: $Exports<'wdio-appium-service/test/integration/smoke_test'>;
}
declare module 'wdio-appium-service/test/integration/wdio.conf.js' {
  declare module.exports: $Exports<'wdio-appium-service/test/integration/wdio.conf'>;
}
declare module 'wdio-appium-service/test/unit/launcher.spec.js' {
  declare module.exports: $Exports<'wdio-appium-service/test/unit/launcher.spec'>;
}
