// flow-typed signature: 1ea640eab36cb284f50dfb839c598650
// flow-typed version: <<STUB>>/wdio-concise-reporter_v^0.1.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wdio-concise-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'wdio-concise-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wdio-concise-reporter/build/reporter' {
  declare module.exports: any;
}

declare module 'wdio-concise-reporter/lib/reporter' {
  declare module.exports: any;
}

declare module 'wdio-concise-reporter/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wdio-concise-reporter/build/reporter.js' {
  declare module.exports: $Exports<'wdio-concise-reporter/build/reporter'>;
}
declare module 'wdio-concise-reporter/lib/reporter.js' {
  declare module.exports: $Exports<'wdio-concise-reporter/lib/reporter'>;
}
declare module 'wdio-concise-reporter/webpack.config.js' {
  declare module.exports: $Exports<'wdio-concise-reporter/webpack.config'>;
}
