// flow-typed signature: 897947269a7d41cb85c1e8f4c999f570
// flow-typed version: <<STUB>>/@percy-io/percy-storybook_v^1.2.3/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@percy-io/percy-storybook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@percy-io/percy-storybook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@percy-io/percy-storybook/bin/percy-storybook' {
  declare module.exports: any;
}

declare module '@percy-io/percy-storybook/lib/args' {
  declare module.exports: any;
}

declare module '@percy-io/percy-storybook/lib/cli' {
  declare module.exports: any;
}

declare module '@percy-io/percy-storybook/lib/constants' {
  declare module.exports: any;
}

declare module '@percy-io/percy-storybook/lib/getMinimumHeight' {
  declare module.exports: any;
}

declare module '@percy-io/percy-storybook/lib/getRtlRegex' {
  declare module.exports: any;
}

declare module '@percy-io/percy-storybook/lib/getStaticAssets' {
  declare module.exports: any;
}

declare module '@percy-io/percy-storybook/lib/getStories' {
  declare module.exports: any;
}

declare module '@percy-io/percy-storybook/lib/getWidths' {
  declare module.exports: any;
}

declare module '@percy-io/percy-storybook/lib/index' {
  declare module.exports: any;
}

declare module '@percy-io/percy-storybook/lib/reactVersion' {
  declare module.exports: any;
}

declare module '@percy-io/percy-storybook/lib/selectStories' {
  declare module.exports: any;
}

declare module '@percy-io/percy-storybook/lib/storybookVersion' {
  declare module.exports: any;
}

declare module '@percy-io/percy-storybook/lib/uploadStories' {
  declare module.exports: any;
}

declare module '@percy-io/percy-storybook/lib/uploadStory' {
  declare module.exports: any;
}

declare module '@percy-io/percy-storybook/lib/uploadStorybook' {
  declare module.exports: any;
}

// Filename aliases
declare module '@percy-io/percy-storybook/bin/percy-storybook.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/bin/percy-storybook'>;
}
declare module '@percy-io/percy-storybook/lib/args.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/lib/args'>;
}
declare module '@percy-io/percy-storybook/lib/cli.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/lib/cli'>;
}
declare module '@percy-io/percy-storybook/lib/constants.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/lib/constants'>;
}
declare module '@percy-io/percy-storybook/lib/getMinimumHeight.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/lib/getMinimumHeight'>;
}
declare module '@percy-io/percy-storybook/lib/getRtlRegex.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/lib/getRtlRegex'>;
}
declare module '@percy-io/percy-storybook/lib/getStaticAssets.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/lib/getStaticAssets'>;
}
declare module '@percy-io/percy-storybook/lib/getStories.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/lib/getStories'>;
}
declare module '@percy-io/percy-storybook/lib/getWidths.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/lib/getWidths'>;
}
declare module '@percy-io/percy-storybook/lib/index.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/lib/index'>;
}
declare module '@percy-io/percy-storybook/lib/reactVersion.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/lib/reactVersion'>;
}
declare module '@percy-io/percy-storybook/lib/selectStories.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/lib/selectStories'>;
}
declare module '@percy-io/percy-storybook/lib/storybookVersion.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/lib/storybookVersion'>;
}
declare module '@percy-io/percy-storybook/lib/uploadStories.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/lib/uploadStories'>;
}
declare module '@percy-io/percy-storybook/lib/uploadStory.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/lib/uploadStory'>;
}
declare module '@percy-io/percy-storybook/lib/uploadStorybook.js' {
  declare module.exports: $Exports<'@percy-io/percy-storybook/lib/uploadStorybook'>;
}
