defaults: &defaults
  working_directory: ~/cocktail-shake-up
  docker:
      - image: circleci/node:8.6.0

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Yarn Install
          command: yarn
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Create persistent workspace
          command: mkdir -p workspace
      - persist_to_workspace:
          root: ~/cocktail-shake-up
          paths:
            - node_modules

  test:
    <<: *defaults

    steps:
      - checkout
      - attach_workspace:
          at: ~/cocktail-shake-up
      - run:
          name: Snyk Authorisation
          command: yarn snyk auth $SNYK_TOKEN
      - run:
          name: Greenkeeper Lockfile Update
          command: yarn greenkeeper-lockfile-update
      - run:
          name: Yarn start
          command: yarn start
          background: true
      - run:
          name: Jest Unit Tests
          command: yarn test
      - run:
          name: Saucelabs System Tests
          command: yarn sauce
      - run:
          command: Greenkeeper Lockfile Upload
          command: yarn greenkeeper-lockfile-upload

  deploy:
    <<: *defaults

    steps:
      - checkout
      - attach_workspace:
          at: ~/cocktail-shake-up
      - run:
          name: Snyk Authorisation
          command: yarn snyk auth $SNYK_TOKEN
      - run:
          name: Yarn Build
          command: yarn build
      - run:
          name: Yarn Deploy
          command: yarn deploy
      - run:
          name: Snyk Monitor
          command: yarn snyk monitor
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_artifacts:
          path: errorShots
          prefix: errorShots
      - store_test_results:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: errorShots
          prefix: errorShots

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
